{"isMarkdown":true,"isTranslated":false,"isActive":true,"flaws":{},"title":"SyntaxError: await is only valid in async functions, async generators and modules","mdn_url":"/en-US/docs/Web/JavaScript/Reference/Errors/Bad_await","locale":"en-US","native":"English (US)","summary":"The JavaScript exception \"await is only valid in async functions, async generators and modules\" occurs when an await expression is used outside of async functions or modules or other async contexts.","popularity":0.0126,"modified":"2023-08-12T02:11:54.000Z","source":{"folder":"en-us/web/javascript/reference/errors/bad_await","github_url":"https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/errors/bad_await/index.md","last_commit_url":"https://github.com/mdn/content/commit/d71b141d2d18b96639547856714df19cefacfebf","filename":"index.md"},"short_title":"SyntaxError: await is only valid in async functions, async generators and modules","parents":[{"uri":"/en-US/docs/Web","title":"References"},{"uri":"/en-US/docs/Web/JavaScript","title":"JavaScript"},{"uri":"/en-US/docs/Web/JavaScript/Reference","title":"Reference"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Errors","title":"JavaScript error reference"},{"uri":"/en-US/docs/Web/JavaScript/Reference/Errors/Bad_await","title":"SyntaxError: await is only valid in async functions, async generators and modules"}],"pageTitle":"SyntaxError: await is only valid in async functions, async generators and modules - JavaScript | MDN","noIndexing":false,"hash":"79d539bb1bdb83c36c57ee73f7bde51e164601ce9739d767ace7b82cd3d00427"}